name: gamestore
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  supabase_flutter: ^2.0.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  mapbox_maps_flutter: ^2.5.3
  cupertino_icons: ^1.0.8
  readmore: ^3.0.0
  http: ^1.1.0
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  flutter_map: ^8.2.2
  latlong2: ^0.9.0
  url_launcher: ^6.2.4
  pdf: ^3.11.0
  printing: ^5.13.0
  share_plus: ^10.0.0
  speech_to_text: ^7.0.0
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
